# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoginGUI(object):
    def setupUi(self, LoginGUI):
        LoginGUI.setObjectName("LoginGUI")
        LoginGUI.resize(1080, 720)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        LoginGUI.setFont(font)
        LoginGUI.setLayoutDirection(QtCore.Qt.LeftToRight)
        LoginGUI.setIconSize(QtCore.QSize(40, 40))
        LoginGUI.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(LoginGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Title = QtWidgets.QLabel(self.centralwidget)
        self.label_Title.setGeometry(QtCore.QRect(110, 40, 851, 91))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_Title.setFont(font)
        self.label_Title.setMouseTracking(False)
        self.label_Title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Title.setObjectName("label_Title")
        self.label_Message = QtWidgets.QLabel(self.centralwidget)
        self.label_Message.setGeometry(QtCore.QRect(310, 550, 471, 31))
        self.label_Message.setText("")
        self.label_Message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Message.setObjectName("label_Message")
        self.widget_backgound = QtWidgets.QWidget(self.centralwidget)
        self.widget_backgound.setGeometry(QtCore.QRect(0, 0, 1080, 720))
        self.widget_backgound.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgb(211, 255, 197), stop:1 rgba(255, 255, 255, 255));\n"
"")
        self.widget_backgound.setObjectName("widget_backgound")
        self.label_UserID = QtWidgets.QLabel(self.widget_backgound)
        self.label_UserID.setGeometry(QtCore.QRect(170, 205, 72, 20))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        self.label_UserID.setFont(font)
        self.label_UserID.setStyleSheet("background-color:rgba(0,0,0,0);")
        self.label_UserID.setObjectName("label_UserID")
        self.lineEdit_UserID = QtWidgets.QLineEdit(self.widget_backgound)
        self.lineEdit_UserID.setGeometry(QtCore.QRect(170, 240, 311, 41))
        self.lineEdit_UserID.setStyleSheet("background-color:rgba(0,0,0,0);")
        self.lineEdit_UserID.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_UserID.setObjectName("lineEdit_UserID")
        self.lineEdit_Password = QtWidgets.QLineEdit(self.widget_backgound)
        self.lineEdit_Password.setGeometry(QtCore.QRect(170, 350, 311, 41))
        self.lineEdit_Password.setStyleSheet("background-color:rgba(0,0,0,0);")
        self.lineEdit_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.label_Password = QtWidgets.QLabel(self.widget_backgound)
        self.label_Password.setGeometry(QtCore.QRect(170, 320, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        self.label_Password.setFont(font)
        self.label_Password.setStyleSheet("background-color:rgba(0,0,0,0);")
        self.label_Password.setObjectName("label_Password")
        self.pushButton_Password = QtWidgets.QPushButton(self.widget_backgound)
        self.pushButton_Password.setGeometry(QtCore.QRect(170, 440, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_Password.setFont(font)
        self.pushButton_Password.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Password.setStyleSheet("background-color:rgb(253, 255, 201)")
        self.pushButton_Password.setFlat(False)
        self.pushButton_Password.setObjectName("pushButton_Password")
        self.pushButton_Face = QtWidgets.QPushButton(self.widget_backgound)
        self.pushButton_Face.setGeometry(QtCore.QRect(690, 220, 241, 241))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(16)
        self.pushButton_Face.setFont(font)
        self.pushButton_Face.setAutoFillBackground(False)
        self.pushButton_Face.setFlat(True)
        self.pushButton_Face.setObjectName("pushButton_Face")
        self.widget_backgound.raise_()
        self.label_Title.raise_()
        self.label_Message.raise_()
        LoginGUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 30))
        self.menubar.setObjectName("menubar")
        LoginGUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginGUI)
        self.statusbar.setObjectName("statusbar")
        LoginGUI.setStatusBar(self.statusbar)

        self.retranslateUi(LoginGUI)
        QtCore.QMetaObject.connectSlotsByName(LoginGUI)

    def retranslateUi(self, LoginGUI):
        _translate = QtCore.QCoreApplication.translate
        LoginGUI.setWindowTitle(_translate("LoginGUI", "Login"))
        self.label_Title.setText(_translate("LoginGUI", "Intelligent Course Management System"))
        self.label_UserID.setText(_translate("LoginGUI", "UserID:"))
        self.label_Password.setText(_translate("LoginGUI", "Password:"))
        self.pushButton_Password.setText(_translate("LoginGUI", "Password Login"))
        self.pushButton_Face.setText(_translate("LoginGUI", ""))

