# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/rebecca/Desktop/timetableTry/table.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Timetable(object):
    def setupUi(self, Timetable):
        Timetable.setObjectName("Timetable")
        Timetable.setEnabled(True)
        Timetable.resize(900, 600)
        Timetable.setAutoFillBackground(False)
        # Timetable.setSizeGripEnabled(True)
        self.label_2 = QtWidgets.QLabel(Timetable)
        self.label_2.setGeometry(QtCore.QRect(373, 10, 275, 30))
        self.label_2.setObjectName("label_2")
        self.table = QtWidgets.QTableWidget(Timetable)
        self.table.setGeometry(QtCore.QRect(169, 60, 711, 491))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setMinimumSize(QtCore.QSize(256, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.table.setFont(font)
        self.table.setMouseTracking(True)
        self.table.setTabletTracking(False)
        self.table.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.table.setAutoFillBackground(False)
        self.table.setStyleSheet("")
        self.table.setShowGrid(True)
        self.table.setObjectName("table")
        self.table.setColumnCount(7)
        self.table.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 0, 0))
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.table.setItem(0, 0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.table.setItem(0, 1, item)

        for i in range(10):
            for j in range(7):
                item = QtWidgets.QTableWidgetItem()
                self.table.setItem(i, j, item)

        self.table.horizontalHeader().setVisible(True)
        self.table.horizontalHeader().setCascadingSectionResizes(True)
        self.table.horizontalHeader().setDefaultSectionSize(90)
        self.table.horizontalHeader().setHighlightSections(True)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.verticalHeader().setVisible(True)
        self.table.verticalHeader().setCascadingSectionResizes(False)
        self.table.verticalHeader().setDefaultSectionSize(47)
        self.label = QtWidgets.QLabel(Timetable)
        self.label.setGeometry(QtCore.QRect(20, 10, 200, 26))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Timetable)
        self.label_3.setGeometry(QtCore.QRect(600, 10, 300, 26))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setIndent(0)
        self.label_3.setObjectName("label_3")
        self.verticalWidget = QtWidgets.QWidget(Timetable)
        self.verticalWidget.setGeometry(QtCore.QRect(20, 60, 141, 491))
        self.verticalWidget.setObjectName("verticalWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.courseButton1 = QtWidgets.QPushButton(self.verticalWidget)
        self.courseButton1.setObjectName("courseButton1")
        self.gridLayout.addWidget(self.courseButton1, 0, 0, 1, 1)
        self.courseButton2 = QtWidgets.QPushButton(self.verticalWidget)
        self.courseButton2.setObjectName("courseButton2")
        self.gridLayout.addWidget(self.courseButton2, 1, 0, 1, 1)
        self.courseButton3 = QtWidgets.QPushButton(self.verticalWidget)
        self.courseButton3.setObjectName("courseButton3")
        self.gridLayout.addWidget(self.courseButton3, 2, 0, 1, 1)
        self.courseButton4 = QtWidgets.QPushButton(self.verticalWidget)
        self.courseButton4.setObjectName("courseButton4")
        self.gridLayout.addWidget(self.courseButton4, 3, 0, 1, 1)
        self.courseButton5 = QtWidgets.QPushButton(self.verticalWidget)
        self.courseButton5.setObjectName("courseButton5")
        self.gridLayout.addWidget(self.courseButton5, 4, 0, 1, 1)
        self.courseButton6 = QtWidgets.QPushButton(self.verticalWidget)
        self.courseButton6.setObjectName("courseButton6")
        self.gridLayout.addWidget(self.courseButton6, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.showCourse = QtWidgets.QLabel(self.verticalWidget)
        self.showCourse.setObjectName("showCourse")
        self.gridLayout.addWidget(self.showCourse, 7, 0, 1, 1, QtCore.Qt.AlignTop)

        self.retranslateUi(Timetable)
        QtCore.QMetaObject.connectSlotsByName(Timetable)

    def retranslateUi(self, Timetable):
        _translate = QtCore.QCoreApplication.translate
        Timetable.setWindowTitle(_translate("Timetable", "Main Page"))
        self.label_2.setText(_translate("Timetable", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#0204ad;\">Weekly Timetable</span></p></body></html>"))
        item = self.table.verticalHeaderItem(0)
        item.setText(_translate("Timetable", "8:30 - 9:30"))
        item = self.table.verticalHeaderItem(1)
        item.setText(_translate("Timetable", "9:30 - 10:30"))
        item = self.table.verticalHeaderItem(2)
        item.setText(_translate("Timetable", "10:30 - 11:30"))
        item = self.table.verticalHeaderItem(3)
        item.setText(_translate("Timetable", "11:30 - 12:30"))
        item = self.table.verticalHeaderItem(4)
        item.setText(_translate("Timetable", "12:30 - 13:30"))
        item = self.table.verticalHeaderItem(5)
        item.setText(_translate("Timetable", "13:30 - 14:30"))
        item = self.table.verticalHeaderItem(6)
        item.setText(_translate("Timetable", "14:30 - 15:30"))
        item = self.table.verticalHeaderItem(7)
        item.setText(_translate("Timetable", "15:30 - 16:30"))
        item = self.table.verticalHeaderItem(8)
        item.setText(_translate("Timetable", "16:30 - 17:30"))
        item = self.table.verticalHeaderItem(9)
        item.setText(_translate("Timetable", "17:30 - 18:30"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Timetable", "Sunday"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Timetable", "Monday"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Timetable", "Tuesday"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("Timetable", "Wednesday"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("Timetable", "Thursday"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("Timetable", "Friday"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("Timetable", "Saturday"))
        __sortingEnabled = self.table.isSortingEnabled()
        self.table.setSortingEnabled(False)
        self.table.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Timetable", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic;\">Welcome, name!</span></p></body></html>"))
        self.label_3.setText(_translate("Timetable", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic;\">Login Time: </span></p></body></html>"))
        self.courseButton1.setText(_translate("Timetable", "course_id"))
        self.courseButton2.setText(_translate("Timetable", "course_id"))
        self.courseButton3.setText(_translate("Timetable", "course_id"))
        self.courseButton4.setText(_translate("Timetable", "course_id"))
        self.courseButton5.setText(_translate("Timetable", "course_id"))
        self.label_4.setText(_translate("Timetable", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Course(s) </span></p><p align=\"center\"><span style=\" font-weight:600;\">in the </span></p><p align=\"center\"><span style=\" font-weight:600;\">next hour:</span></p></body></html>"))
        self.showCourse.setText(_translate("Timetable", "<html><head/><body><p align=\"center\">(None)</p></body></html>"))

